organizationID: a7196ee5-5189-41ea-b479-c04fdb9858ec
clusterID: 6b54951c-3031-4372-af53-b50cae9d8ac7
disabledProviders: []
mqtt:
  broker: "tls://axeofcqtiseyl-ats.iot.eu-central-1.amazonaws.com:8883"
  topic: "kubeadvisor/clusterdata/v1"
  qos: 1
  caCertificate: "/etc/certs/ca.pem"
  tlsKeyFile: "/etc/certs/private.key" # "path/to/tls/key"
  tlsCertificateFile: "/etc/certs/cert.pem" # "path/to/tls/certificate"
  username: ""
  password: ""
  clientID: "basicPubSub"
  cleanSession: false
