organizationID: a7196ee5-5189-41ea-b479-c04fdb9858ec
clusterID: 6b54951c-3031-4372-af53-b50cae9d8ac7
disabledProviders: []
mqtt:
  broker: "tcp://test.mosquitto.org:1884"
  topic: "robert/robertstestsensor/message/testmessage"
  qos: 2
  tlsKeyFile: "" # "path/to/tls/key"
  tlsCertificateFile: "" # "path/to/tls/certificate"
  username: "rw"
  password: "readwrite"
  cleanSession: true