apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-advisor-agent
automountServiceAccountToken: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-advisor-agent
rules:
- apiGroups: [""]
  resources: ["namespaces", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: kube-advisor-agent
subjects:
- kind: ServiceAccount
  name: kube-advisor-agent 
  namespace: kube-advisor
roleRef:
  kind: ClusterRole
  name: kube-advisor-agent
  apiGroup: rbac.authorization.k8s.io