apiVersion: v1
kind: Namespace
metadata:
  name: business-api

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-with-default-backend
  namespace: business-api
  labels:
    app: business-api
spec:
  defaultBackend:
    service:
      name: nginx-service-non-existent
      port:
        number: 80